// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1621

#include "loggerI.h"

// Implementation skeleton constructor
LoggerServer_Logger_i::LoggerServer_Logger_i ()
{
}
[canoa.alexandre@ene02-ep-pucpr logger_v2]$ cat loggerI.h 
// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1567

#ifndef LOGGERI_2H7ZZK_H_
#define LOGGERI_2H7ZZK_H_

#include "loggerS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  LoggerServer_Logger_i
  : public virtual POA_LoggerServer::Logger
{
public:
  // Constructor
  LoggerServer_Logger_i ();

  // Destructor
  virtual ~LoggerServer_Logger_i ();

  virtual
  ::CORBA::Boolean verbose ();

  virtual
  void verbose (
    ::CORBA::Boolean verbose);

  virtual
  void log (
    ::LoggerServer::Severidade severidade,
    const std::string endereco,
    const std::string pid,
    const std::string hora,
    const std::string msg);
};


#endif /* LOGGERI_H_  */
